### ISSUE TITLE
Не работает 

### ISSUE THREAD

**Issue by nkonshin** [SP-l33t/Paws-Hybrid#1]
Друг, подскажи пожалуйста как пофиксить 
Конкретно этот скрин с Goats, там просто issues закрыты 
но тоже самое почему-то во всех ботах от тебя 
<img width="940" alt="Снимок экрана 2024-11-24 в 01 39 39" src="https://github.com/user-attachments/assets/cfadfb82-517d-46cc-8784-6cba12598b31">
<img width="823" alt="Снимок экрана 2024-11-24 в 01 39 53" src="https://github.com/user-attachments/assets/16a2495c-2fb3-4e50-b801-add2ac2b7c99">

Прокси указаны в классическом формате, как и во всех других ботах.
Сессии валидные.
джэйсон файл после запуска вроде создается корректно, несколько раз уже удалял его для пересоздания, но выдает такую же ошибку каждый раз

**Comment by SP-l33t** [comment]
Привет. Недавно сталкивался с таким. У тебя кажется в названии сессии есть точка.
Это вызывает проблемы.
Переименуй файл сессии, начинающийся на 9 на другой, где не будет точек (кроме расширения)
